{
 "title": "Market data tutorial",
 "time": { "from": "now-20m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instrument",
    "label": "instrument",
    "query": "SELECT DISTINCT imnt FROM market_data;"
   },
   {
    "name": "market",
    "label": "market",
    "query": "SELECT DISTINCT market FROM market_data;"
   }
  ]
 },
 "panels": [
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prices",
   "type": "candlestick",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  close_time AS \"time\",\n  close_px,\n  open_px,\n  high_px,\n  low_px,\n  vwap,\n  notional\nFROM market_data\nWHERE\n  market = '$market' AND\n  imnt = '$instrument'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Bulldozer Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  rate\nFROM bulldozer_rate\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Bulldozer Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  rate\nFROM bulldozer_rate\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Orders",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "rawSql": "SELECT * from orders;" }
   ]
  },
  {
   "title": "Order events",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT (info->'orderType'->'limit')::text as price, (info->'quantity')::text as quantity, (info->'orderSide')::text as side, strategy, oms, strgordid, pubtime, seqnum, type, pubseq from order_events\nWHERE type = 'new'\nUNION\nSELECT NULL as price, (info->'leaves')::text as quantity, NULL as side, strategy, oms, strgordid, pubtime, seqnum, type, pubseq from order_events\nWHERE type = 'cancel'\nUNION\nSELECT NULL as price, NULL as quantity, NULL as side, strategy, oms, strgordid, pubtime, seqnum, type, pubseq from order_events\nWHERE NOT (type = 'new' OR type = 'cancel')\nORDER BY pubseq ASC;"
    }
   ]
  },
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } }
 ]
}