[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
pidfile=/tmp/supervisord.pid
nodaemon=true
silent=true

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:deploy]
command=/bin/bash -c "python3 deploy.py --cfg ./cfg.json && cat"
priority=1
autorestart=false
stdout_syslog=true
stderr_syslog=true

[program:bulldozer]
command=yamal-run -c ./bulldozer_coinbase.ini -s main
priority=2
autorestart=false
stdout_syslog=true
stderr_syslog=true

[program:bulldozer2postgresql]
command=python3 bulldozer2postgresql.py --database %(ENV_POSTGRES_NAME)s --user %(ENV_POSTGRES_USER)s --password %(ENV_POSTGRES_PASSWORD)s --host %(ENV_POSTGRES_HOST)s --port %(ENV_POSTGRES_PORT)s --ytp ./ore_coinbase_l2.ytp
priority=3
autorestart=false
stdout_syslog=true
stderr_syslog=true

[program:postgresql]
command=python3 postgres.py --database %(ENV_POSTGRES_NAME)s --user %(ENV_POSTGRES_USER)s --password %(ENV_POSTGRES_PASSWORD)s --host %(ENV_POSTGRES_HOST)s --port %(ENV_POSTGRES_PORT)s --period %(ENV_BARS_PERIOD)s --cfg ./cfg.json
priority=3
autorestart=false
stdout_syslog=true
stderr_syslog=true

[eventlistener:stopsupervisor]
command=./stop-supervisor.sh
events=PROCESS_STATE_STOPPED, PROCESS_STATE_EXITED, PROCESS_STATE_FATAL
stdout_syslog=true
stderr_syslog=true
