{
 "title": "Bulldozer Rate",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instrument",
    "label": "Instrument",
    "query": "SELECT DISTINCT imnt FROM market_data;"
   },
   {
    "name": "market",
    "label": "market",
    "query": "SELECT DISTINCT market FROM market_data;"
   }
  ]
 },
 "panels": [
  {
   "title": "open/close price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  open_px,\n  close_px\nFROM market_data\nWHERE\n  market = '$market' AND\n  imnt = '$instrument'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "high/low price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  low_px,\n  high_px\nFROM market_data\nWHERE\n  market = '$market' AND\n  imnt = '$instrument'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "VWAP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  vwap\nFROM market_data\nWHERE\n  market = '$market' AND\n  imnt = '$instrument'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Bulldozer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  rate\nFROM bulldozer_rate\nORDER BY 1"
    }
   ]
  }
 ]
}