# COPYRIGHT (c) 2019-2023 by Featuremine Corporation.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: CMake PR

on:
  pull_request:

permissions: write-all

jobs:
  utility:
    runs-on: ubuntu-20.04
    outputs:
      release-check: ${{ steps.release-check.outputs.release-check }}

    steps:
    - name: Utility tasks
      id: release-check
      uses: featuremine/actions/utility@v2
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        utility_token: ${{ secrets.UTILITY_COMMIT_TOKEN }}

  build-manylinux:
    needs: utility
    runs-on: ubuntu-20.04
    env:
      SSL_CERT_DIR: /usr/lib/ssl/certs
    container:
      image: public.ecr.aws/p0w8t0l8/ci-hosted-gh-centos7-gcc10.2.0

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build ${{ github.event.repository.name }} with fm gcc
      uses: featuremine/actions/package/build@v2
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        docs: true
        wheel: true
        upload: ${{ needs.utility.outputs.release-check == 'release' }}

  build-macos:
    needs: utility
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: brew install pkg-config cmake openssl python

    - name: Build ${{ github.event.repository.name }} with fm gcc
      uses: featuremine/actions/package/build@v2
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        docs: false
        wheel: true
        upload: ${{ needs.utility.outputs.release-check == 'release' }}

  build-macos-13-arm:
    needs: utility
    if: needs.utility.outputs.release-check == 'release'
    runs-on: macos-13-xlarge

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: brew install pkg-config cmake openssl python

    - name: Build ${{ github.event.repository.name }} with fm gcc
      uses: featuremine/actions/package/build@v2
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        docs: false
        wheel: true
        upload: ${{ needs.utility.outputs.release-check == 'release' }}
